### ISSUE TITLE
[Suggestion:] Return to the point of death with a command

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#43]
**Is your feature request related to a problem? Please describe.**
I have been thinking about this idea for a while and I do not know if you like it because I do not know if it fits with this plugin, would be to add a command which the player can use to die (eg /back) and if possible also have a setting in which to edit the time limit that has to return to the point of his death. Also that the player could only return 1 time to the point where he has died

```yml
#/back command for  return to the point where you have died [true | false]
back-death-command: "true"
#maximum time in which the player can return to the point of death, setting it to "0" will make it possible for the player to use it whenever he wants
back-time: 15
```

**Describe the solution you'd like**
X

**Describe alternatives you've considered**
X

**Additional context**
X
